/**
 * Registre curé des méthodes des **services natifs** Google Apps Script.
 * Source : doc Google + DefinitelyTyped (`@types/google-apps-script`).
 *
 * Format : `TYPE → { METHOD → { returns: TYPE_NAME } }`
 *
 * Quand `returns` est un type connu, la chaîne suit. Quand `returns` est
 * `'unknown'`, la validation s'arrête honnêtement (le reste de la chaîne
 * remonte en `coverage.unresolved`, pas en faux positif).
 *
 * Quand un type *contient* `[]` (ex: `Sheet[]`), la chaîne s'arrête : l'API
 * d'indexation n'est pas traversée par cette V1 — c'est honnête plutôt qu'arbitraire.
 *
 * Couverture : pas exhaustive ; on couvre les ~95 % de surface utilisés en
 * pratique. Une méthode absente du registre **N'EST PAS** signalée
 * (silencieux) parce qu'on ne sait pas — voir validate-api.ts.
 */

export interface MethodSig {
  returns: string;
}

export type GasApiRegistry = Record<string, Record<string, MethodSig>>;

export const GAS_API: GasApiRegistry = {
  // ─── SpreadsheetApp ──────────────────────────────────────────────────
  SpreadsheetApp: {
    create: { returns: 'Spreadsheet' },
    getActive: { returns: 'Spreadsheet' },
    getActiveSpreadsheet: { returns: 'Spreadsheet' },
    getActiveSheet: { returns: 'Sheet' },
    getActiveRange: { returns: 'Range' },
    getActiveRangeList: { returns: 'unknown' },
    openById: { returns: 'Spreadsheet' },
    openByUrl: { returns: 'Spreadsheet' },
    open: { returns: 'Spreadsheet' },
    flush: { returns: 'void' },
    newDataValidation: { returns: 'unknown' },
    newConditionalFormatRule: { returns: 'unknown' },
    newFilterCriteria: { returns: 'unknown' },
  },
  Spreadsheet: {
    getName: { returns: 'string' },
    rename: { returns: 'void' },
    getId: { returns: 'string' },
    getUrl: { returns: 'string' },
    getActiveSheet: { returns: 'Sheet' },
    getSheets: { returns: 'Sheet[]' },
    getSheetByName: { returns: 'Sheet' },
    getSheetId: { returns: 'number' },
    insertSheet: { returns: 'Sheet' },
    deleteSheet: { returns: 'void' },
    duplicateActiveSheet: { returns: 'Sheet' },
    setActiveSheet: { returns: 'Sheet' },
    moveActiveSheet: { returns: 'void' },
    getRange: { returns: 'Range' },
    getRangeByName: { returns: 'Range' },
    getRangeList: { returns: 'unknown' },
    getDataRange: { returns: 'Range' },
    getLastRow: { returns: 'number' },
    getLastColumn: { returns: 'number' },
    getNumSheets: { returns: 'number' },
    addEditor: { returns: 'Spreadsheet' },
    removeEditor: { returns: 'Spreadsheet' },
    getOwner: { returns: 'unknown' },
    getEditors: { returns: 'unknown' },
    getViewers: { returns: 'unknown' },
    setSpreadsheetTimeZone: { returns: 'void' },
    getSpreadsheetTimeZone: { returns: 'string' },
    setSpreadsheetLocale: { returns: 'void' },
    getSpreadsheetLocale: { returns: 'string' },
    setNamedRange: { returns: 'void' },
    getNamedRanges: { returns: 'unknown' },
    removeNamedRange: { returns: 'void' },
    insertImage: { returns: 'unknown' },
    insertRowsBefore: { returns: 'Sheet' },
    insertRowsAfter: { returns: 'Sheet' },
    insertColumnsBefore: { returns: 'Sheet' },
    insertColumnsAfter: { returns: 'Sheet' },
    deleteRow: { returns: 'Sheet' },
    deleteColumn: { returns: 'Sheet' },
    toast: { returns: 'void' },
    show: { returns: 'void' },
  },
  Sheet: {
    getName: { returns: 'string' },
    setName: { returns: 'Sheet' },
    getSheetId: { returns: 'number' },
    getIndex: { returns: 'number' },
    getParent: { returns: 'Spreadsheet' },
    activate: { returns: 'Sheet' },
    clear: { returns: 'Sheet' },
    clearContents: { returns: 'Sheet' },
    clearFormats: { returns: 'Sheet' },
    clearNotes: { returns: 'Sheet' },
    copyTo: { returns: 'Sheet' },
    getRange: { returns: 'Range' },
    getRangeList: { returns: 'unknown' },
    getDataRange: { returns: 'Range' },
    getActiveRange: { returns: 'Range' },
    getActiveCell: { returns: 'Range' },
    getLastRow: { returns: 'number' },
    getLastColumn: { returns: 'number' },
    getMaxRows: { returns: 'number' },
    getMaxColumns: { returns: 'number' },
    getFrozenRows: { returns: 'number' },
    getFrozenColumns: { returns: 'number' },
    setFrozenRows: { returns: 'Sheet' },
    setFrozenColumns: { returns: 'Sheet' },
    insertRowAfter: { returns: 'Sheet' },
    insertRowBefore: { returns: 'Sheet' },
    insertRowsAfter: { returns: 'Sheet' },
    insertRowsBefore: { returns: 'Sheet' },
    insertColumnAfter: { returns: 'Sheet' },
    insertColumnBefore: { returns: 'Sheet' },
    insertColumnsAfter: { returns: 'Sheet' },
    insertColumnsBefore: { returns: 'Sheet' },
    deleteRow: { returns: 'Sheet' },
    deleteRows: { returns: 'Sheet' },
    deleteColumn: { returns: 'Sheet' },
    deleteColumns: { returns: 'Sheet' },
    appendRow: { returns: 'Sheet' },
    autoResizeColumn: { returns: 'Sheet' },
    autoResizeColumns: { returns: 'Sheet' },
    autoResizeRows: { returns: 'Sheet' },
    hideRows: { returns: 'void' },
    hideColumns: { returns: 'void' },
    showRows: { returns: 'void' },
    showColumns: { returns: 'void' },
    hideSheet: { returns: 'Sheet' },
    showSheet: { returns: 'Sheet' },
    isSheetHidden: { returns: 'boolean' },
    getFormUrl: { returns: 'string' },
    setColumnWidth: { returns: 'Sheet' },
    setColumnWidths: { returns: 'Sheet' },
    setRowHeight: { returns: 'Sheet' },
    setRowHeights: { returns: 'Sheet' },
    sort: { returns: 'Sheet' },
    setActiveRange: { returns: 'Range' },
    setActiveSelection: { returns: 'Range' },
    setActiveCell: { returns: 'Range' },
    protect: { returns: 'unknown' },
    getProtections: { returns: 'unknown' },
    getCharts: { returns: 'unknown' },
    newChart: { returns: 'unknown' },
    insertChart: { returns: 'void' },
    removeChart: { returns: 'void' },
    getImages: { returns: 'unknown' },
  },
  Range: {
    getValue: { returns: 'unknown' },
    getValues: { returns: 'unknown' },
    getDisplayValue: { returns: 'string' },
    getDisplayValues: { returns: 'unknown' },
    setValue: { returns: 'Range' },
    setValues: { returns: 'Range' },
    setFormula: { returns: 'Range' },
    setFormulas: { returns: 'Range' },
    getFormula: { returns: 'string' },
    getFormulas: { returns: 'unknown' },
    getFormulaR1C1: { returns: 'string' },
    setFormulaR1C1: { returns: 'Range' },
    getA1Notation: { returns: 'string' },
    getRow: { returns: 'number' },
    getColumn: { returns: 'number' },
    getLastRow: { returns: 'number' },
    getLastColumn: { returns: 'number' },
    getNumRows: { returns: 'number' },
    getNumColumns: { returns: 'number' },
    getHeight: { returns: 'number' },
    getWidth: { returns: 'number' },
    getCell: { returns: 'Range' },
    offset: { returns: 'Range' },
    getSheet: { returns: 'Sheet' },
    getBackground: { returns: 'string' },
    getBackgrounds: { returns: 'unknown' },
    setBackground: { returns: 'Range' },
    setBackgrounds: { returns: 'Range' },
    setBackgroundRGB: { returns: 'Range' },
    getFontColor: { returns: 'string' },
    setFontColor: { returns: 'Range' },
    setFontColors: { returns: 'Range' },
    setFontWeight: { returns: 'Range' },
    setFontWeights: { returns: 'Range' },
    setFontStyle: { returns: 'Range' },
    setFontSize: { returns: 'Range' },
    setFontFamily: { returns: 'Range' },
    setHorizontalAlignment: { returns: 'Range' },
    setVerticalAlignment: { returns: 'Range' },
    setNumberFormat: { returns: 'Range' },
    setNumberFormats: { returns: 'Range' },
    setNote: { returns: 'Range' },
    setNotes: { returns: 'Range' },
    getNote: { returns: 'string' },
    clear: { returns: 'Range' },
    clearContent: { returns: 'Range' },
    clearFormat: { returns: 'Range' },
    clearNote: { returns: 'Range' },
    clearDataValidations: { returns: 'Range' },
    copyTo: { returns: 'void' },
    copyValuesToRange: { returns: 'void' },
    copyFormatToRange: { returns: 'void' },
    moveTo: { returns: 'void' },
    sort: { returns: 'Range' },
    activate: { returns: 'Range' },
    activateAsCurrentCell: { returns: 'Range' },
    setBorder: { returns: 'Range' },
    setBorders: { returns: 'Range' },
    setWrap: { returns: 'Range' },
    setWraps: { returns: 'Range' },
    setWrapStrategy: { returns: 'Range' },
    setVerticalText: { returns: 'Range' },
    setTextRotation: { returns: 'Range' },
    setTextDirection: { returns: 'Range' },
    getDataValidation: { returns: 'unknown' },
    setDataValidation: { returns: 'Range' },
    getMergedRanges: { returns: 'unknown' },
    merge: { returns: 'Range' },
    mergeAcross: { returns: 'Range' },
    mergeVertically: { returns: 'Range' },
    breakApart: { returns: 'Range' },
    isBlank: { returns: 'boolean' },
    isPartOfMerge: { returns: 'boolean' },
    createFilter: { returns: 'unknown' },
    getFilter: { returns: 'unknown' },
    createTextFinder: { returns: 'unknown' },
    randomize: { returns: 'Range' },
    insertCheckboxes: { returns: 'Range' },
    removeCheckboxes: { returns: 'Range' },
    isChecked: { returns: 'boolean' },
    check: { returns: 'Range' },
    uncheck: { returns: 'Range' },
  },

  // ─── DriveApp ────────────────────────────────────────────────────────
  DriveApp: {
    getRootFolder: { returns: 'Folder' },
    getFolderById: { returns: 'Folder' },
    getFolderByIdAndResourceKey: { returns: 'Folder' },
    getFoldersByName: { returns: 'unknown' },
    getFolders: { returns: 'unknown' },
    getFileById: { returns: 'File' },
    getFileByIdAndResourceKey: { returns: 'File' },
    getFilesByName: { returns: 'unknown' },
    getFilesByType: { returns: 'unknown' },
    getFiles: { returns: 'unknown' },
    createFile: { returns: 'File' },
    createFolder: { returns: 'Folder' },
    createShortcut: { returns: 'File' },
    searchFiles: { returns: 'unknown' },
    searchFolders: { returns: 'unknown' },
    getTrashedFiles: { returns: 'unknown' },
    getTrashedFolders: { returns: 'unknown' },
    getStorageUsed: { returns: 'number' },
    getStorageLimit: { returns: 'number' },
    enforceSingleParent: { returns: 'void' },
  },
  Folder: {
    getId: { returns: 'string' },
    getName: { returns: 'string' },
    getUrl: { returns: 'string' },
    setName: { returns: 'Folder' },
    getDateCreated: { returns: 'unknown' },
    getLastUpdated: { returns: 'unknown' },
    getOwner: { returns: 'unknown' },
    getDescription: { returns: 'string' },
    setDescription: { returns: 'Folder' },
    getParents: { returns: 'unknown' },
    getFiles: { returns: 'unknown' },
    getFilesByName: { returns: 'unknown' },
    getFilesByType: { returns: 'unknown' },
    getFolders: { returns: 'unknown' },
    getFoldersByName: { returns: 'unknown' },
    createFile: { returns: 'File' },
    createFolder: { returns: 'Folder' },
    moveTo: { returns: 'Folder' },
    isStarred: { returns: 'boolean' },
    setStarred: { returns: 'Folder' },
    isTrashed: { returns: 'boolean' },
    setTrashed: { returns: 'Folder' },
    addEditor: { returns: 'Folder' },
    addViewer: { returns: 'Folder' },
    addCommenter: { returns: 'Folder' },
    removeEditor: { returns: 'Folder' },
    removeViewer: { returns: 'Folder' },
    removeCommenter: { returns: 'Folder' },
    setSharing: { returns: 'Folder' },
    getEditors: { returns: 'unknown' },
    getViewers: { returns: 'unknown' },
    getSize: { returns: 'number' },
    getSharingAccess: { returns: 'unknown' },
    getSharingPermission: { returns: 'unknown' },
  },
  File: {
    getId: { returns: 'string' },
    getName: { returns: 'string' },
    getUrl: { returns: 'string' },
    setName: { returns: 'File' },
    getBlob: { returns: 'Blob' },
    getAs: { returns: 'Blob' },
    getMimeType: { returns: 'string' },
    getSize: { returns: 'number' },
    getDateCreated: { returns: 'unknown' },
    getLastUpdated: { returns: 'unknown' },
    getOwner: { returns: 'unknown' },
    getDescription: { returns: 'string' },
    setDescription: { returns: 'File' },
    getParents: { returns: 'unknown' },
    moveTo: { returns: 'File' },
    makeCopy: { returns: 'File' },
    addEditor: { returns: 'File' },
    addViewer: { returns: 'File' },
    addCommenter: { returns: 'File' },
    removeEditor: { returns: 'File' },
    removeViewer: { returns: 'File' },
    removeCommenter: { returns: 'File' },
    setSharing: { returns: 'File' },
    setOwner: { returns: 'File' },
    getEditors: { returns: 'unknown' },
    getViewers: { returns: 'unknown' },
    setTrashed: { returns: 'File' },
    isTrashed: { returns: 'boolean' },
    setStarred: { returns: 'File' },
    isStarred: { returns: 'boolean' },
    setContent: { returns: 'File' },
    setShareableByEditors: { returns: 'File' },
    getDownloadUrl: { returns: 'string' },
    revokePermissions: { returns: 'File' },
    getResourceKey: { returns: 'string' },
    getSecurityUpdateEligible: { returns: 'boolean' },
  },
  Blob: {
    getName: { returns: 'string' },
    setName: { returns: 'Blob' },
    getBytes: { returns: 'unknown' },
    setBytes: { returns: 'Blob' },
    getDataAsString: { returns: 'string' },
    setDataFromString: { returns: 'Blob' },
    getContentType: { returns: 'string' },
    setContentType: { returns: 'Blob' },
    copyBlob: { returns: 'Blob' },
    getAs: { returns: 'Blob' },
    isGoogleType: { returns: 'boolean' },
  },

  // ─── GmailApp / MailApp ──────────────────────────────────────────────
  GmailApp: {
    sendEmail: { returns: 'GmailApp' },
    getAliases: { returns: 'unknown' },
    getInboxThreads: { returns: 'unknown' },
    getInboxUnreadCount: { returns: 'number' },
    getThreadById: { returns: 'unknown' },
    getMessageById: { returns: 'unknown' },
    getDraft: { returns: 'unknown' },
    getDrafts: { returns: 'unknown' },
    createDraft: { returns: 'unknown' },
    search: { returns: 'unknown' },
    getStarredThreads: { returns: 'unknown' },
    getSpamThreads: { returns: 'unknown' },
    getTrashThreads: { returns: 'unknown' },
    getChatThreads: { returns: 'unknown' },
    getPriorityInboxThreads: { returns: 'unknown' },
    getUserLabels: { returns: 'unknown' },
    getUserLabelByName: { returns: 'unknown' },
    createLabel: { returns: 'unknown' },
    markMessageRead: { returns: 'unknown' },
    markThreadRead: { returns: 'unknown' },
    markMessageUnread: { returns: 'unknown' },
    starMessage: { returns: 'unknown' },
    starMessages: { returns: 'unknown' },
    unstarMessage: { returns: 'unknown' },
    moveMessageToTrash: { returns: 'unknown' },
    moveThreadToTrash: { returns: 'unknown' },
    refreshThread: { returns: 'unknown' },
    refreshMessage: { returns: 'unknown' },
    refreshMessages: { returns: 'unknown' },
    refreshThreads: { returns: 'unknown' },
  },
  MailApp: {
    sendEmail: { returns: 'void' },
    getRemainingDailyQuota: { returns: 'number' },
  },

  // ─── PropertiesService / CacheService / LockService ──────────────────
  PropertiesService: {
    getScriptProperties: { returns: 'Properties' },
    getUserProperties: { returns: 'Properties' },
    getDocumentProperties: { returns: 'Properties' },
  },
  Properties: {
    getProperty: { returns: 'string' },
    getProperties: { returns: 'unknown' },
    getKeys: { returns: 'unknown' },
    setProperty: { returns: 'Properties' },
    setProperties: { returns: 'Properties' },
    deleteProperty: { returns: 'Properties' },
    deleteAllProperties: { returns: 'Properties' },
  },
  CacheService: {
    getScriptCache: { returns: 'Cache' },
    getUserCache: { returns: 'Cache' },
    getDocumentCache: { returns: 'Cache' },
  },
  Cache: {
    get: { returns: 'string' },
    getAll: { returns: 'unknown' },
    put: { returns: 'void' },
    putAll: { returns: 'void' },
    remove: { returns: 'void' },
    removeAll: { returns: 'void' },
  },
  LockService: {
    getScriptLock: { returns: 'Lock' },
    getUserLock: { returns: 'Lock' },
    getDocumentLock: { returns: 'Lock' },
  },
  Lock: {
    tryLock: { returns: 'boolean' },
    waitLock: { returns: 'void' },
    hasLock: { returns: 'boolean' },
    releaseLock: { returns: 'void' },
  },

  // ─── ScriptApp ───────────────────────────────────────────────────────
  ScriptApp: {
    newTrigger: { returns: 'TriggerBuilder' },
    getProjectTriggers: { returns: 'unknown' },
    getUserTriggers: { returns: 'unknown' },
    deleteTrigger: { returns: 'void' },
    getOAuthToken: { returns: 'string' },
    getIdentityToken: { returns: 'string' },
    getScriptId: { returns: 'string' },
    invalidateAuth: { returns: 'void' },
    requireAllScopes: { returns: 'void' },
    requireScopesForCurrentUser: { returns: 'void' },
    newStateToken: { returns: 'unknown' },
    getAuthorizationInfo: { returns: 'unknown' },
    getInstallationSource: { returns: 'unknown' },
    getService: { returns: 'unknown' },
  },
  TriggerBuilder: {
    timeBased: { returns: 'ClockTriggerBuilder' },
    forSpreadsheet: { returns: 'SpreadsheetTriggerBuilder' },
    forDocument: { returns: 'DocumentTriggerBuilder' },
    forForm: { returns: 'FormTriggerBuilder' },
    forUserCalendar: { returns: 'CalendarTriggerBuilder' },
  },
  ClockTriggerBuilder: {
    after: { returns: 'ClockTriggerBuilder' },
    at: { returns: 'ClockTriggerBuilder' },
    atDate: { returns: 'ClockTriggerBuilder' },
    atHour: { returns: 'ClockTriggerBuilder' },
    nearMinute: { returns: 'ClockTriggerBuilder' },
    inTimezone: { returns: 'ClockTriggerBuilder' },
    everyMinutes: { returns: 'ClockTriggerBuilder' },
    everyHours: { returns: 'ClockTriggerBuilder' },
    everyDays: { returns: 'ClockTriggerBuilder' },
    everyWeeks: { returns: 'ClockTriggerBuilder' },
    onMonthDay: { returns: 'ClockTriggerBuilder' },
    onWeekDay: { returns: 'ClockTriggerBuilder' },
    create: { returns: 'Trigger' },
  },
  SpreadsheetTriggerBuilder: {
    onEdit: { returns: 'SpreadsheetTriggerBuilder' },
    onChange: { returns: 'SpreadsheetTriggerBuilder' },
    onFormSubmit: { returns: 'SpreadsheetTriggerBuilder' },
    onOpen: { returns: 'SpreadsheetTriggerBuilder' },
    create: { returns: 'Trigger' },
  },
  DocumentTriggerBuilder: {
    onOpen: { returns: 'DocumentTriggerBuilder' },
    create: { returns: 'Trigger' },
  },
  FormTriggerBuilder: {
    onFormSubmit: { returns: 'FormTriggerBuilder' },
    onOpen: { returns: 'FormTriggerBuilder' },
    create: { returns: 'Trigger' },
  },
  CalendarTriggerBuilder: {
    onEventUpdated: { returns: 'CalendarTriggerBuilder' },
    create: { returns: 'Trigger' },
  },
  Trigger: {
    getUniqueId: { returns: 'string' },
    getHandlerFunction: { returns: 'string' },
    getEventType: { returns: 'unknown' },
    getTriggerSource: { returns: 'unknown' },
    getTriggerSourceId: { returns: 'string' },
  },

  // ─── Utilities ───────────────────────────────────────────────────────
  Utilities: {
    base64Decode: { returns: 'unknown' },
    base64DecodeWebSafe: { returns: 'unknown' },
    base64Encode: { returns: 'string' },
    base64EncodeWebSafe: { returns: 'string' },
    computeDigest: { returns: 'unknown' },
    computeHmacSha256Signature: { returns: 'unknown' },
    computeHmacSignature: { returns: 'unknown' },
    computeRsaSha1Signature: { returns: 'unknown' },
    computeRsaSha256Signature: { returns: 'unknown' },
    formatDate: { returns: 'string' },
    formatString: { returns: 'string' },
    getUuid: { returns: 'string' },
    gzip: { returns: 'Blob' },
    jsonParse: { returns: 'unknown' },
    jsonStringify: { returns: 'string' },
    newBlob: { returns: 'Blob' },
    parseCsv: { returns: 'unknown' },
    parseDate: { returns: 'unknown' },
    sleep: { returns: 'void' },
    ungzip: { returns: 'Blob' },
    unzip: { returns: 'unknown' },
    zip: { returns: 'Blob' },
  },

  // ─── Session ─────────────────────────────────────────────────────────
  Session: {
    getActiveUser: { returns: 'User' },
    getEffectiveUser: { returns: 'User' },
    getTemporaryActiveUserKey: { returns: 'string' },
    getActiveUserLocale: { returns: 'string' },
    getScriptTimeZone: { returns: 'string' },
    getTimeZone: { returns: 'string' },
  },
  User: {
    getEmail: { returns: 'string' },
    getUserLoginId: { returns: 'string' },
  },

  // ─── HtmlService ─────────────────────────────────────────────────────
  HtmlService: {
    createHtmlOutput: { returns: 'HtmlOutput' },
    createHtmlOutputFromFile: { returns: 'HtmlOutput' },
    createTemplate: { returns: 'HtmlTemplate' },
    createTemplateFromFile: { returns: 'HtmlTemplate' },
    getUserAgent: { returns: 'string' },
  },
  HtmlOutput: {
    append: { returns: 'HtmlOutput' },
    appendUntrusted: { returns: 'HtmlOutput' },
    clear: { returns: 'HtmlOutput' },
    getAs: { returns: 'Blob' },
    getBlob: { returns: 'Blob' },
    getContent: { returns: 'string' },
    getFaviconUrl: { returns: 'string' },
    getHeight: { returns: 'number' },
    getMetaTags: { returns: 'unknown' },
    getTitle: { returns: 'string' },
    getWidth: { returns: 'number' },
    setContent: { returns: 'HtmlOutput' },
    setFaviconUrl: { returns: 'HtmlOutput' },
    setHeight: { returns: 'HtmlOutput' },
    setSandboxMode: { returns: 'HtmlOutput' },
    setTitle: { returns: 'HtmlOutput' },
    setWidth: { returns: 'HtmlOutput' },
    setXFrameOptionsMode: { returns: 'HtmlOutput' },
    addMetaTag: { returns: 'HtmlOutput' },
  },
  HtmlTemplate: {
    evaluate: { returns: 'HtmlOutput' },
    getCode: { returns: 'string' },
    getCodeWithComments: { returns: 'string' },
    getRawContent: { returns: 'string' },
  },

  // ─── ContentService ──────────────────────────────────────────────────
  ContentService: {
    createTextOutput: { returns: 'TextOutput' },
  },
  TextOutput: {
    append: { returns: 'TextOutput' },
    clear: { returns: 'TextOutput' },
    downloadAsFile: { returns: 'TextOutput' },
    getContent: { returns: 'string' },
    getFileName: { returns: 'string' },
    getMimeType: { returns: 'unknown' },
    setContent: { returns: 'TextOutput' },
    setMimeType: { returns: 'TextOutput' },
  },

  // ─── UrlFetchApp ─────────────────────────────────────────────────────
  UrlFetchApp: {
    fetch: { returns: 'HTTPResponse' },
    fetchAll: { returns: 'unknown' },
    getRequest: { returns: 'unknown' },
  },
  HTTPResponse: {
    getAllHeaders: { returns: 'unknown' },
    getAs: { returns: 'Blob' },
    getBlob: { returns: 'Blob' },
    getContent: { returns: 'unknown' },
    getContentText: { returns: 'string' },
    getHeaders: { returns: 'unknown' },
    getResponseCode: { returns: 'number' },
  },

  // ─── Logger / console ────────────────────────────────────────────────
  Logger: {
    log: { returns: 'Logger' },
    clear: { returns: 'void' },
    getLog: { returns: 'string' },
  },

  // ─── DocumentApp (basique) ───────────────────────────────────────────
  DocumentApp: {
    create: { returns: 'Document' },
    getActiveDocument: { returns: 'Document' },
    openById: { returns: 'Document' },
    openByUrl: { returns: 'Document' },
    getUi: { returns: 'unknown' },
  },
  Document: {
    getId: { returns: 'string' },
    getName: { returns: 'string' },
    getUrl: { returns: 'string' },
    setName: { returns: 'Document' },
    getBody: { returns: 'Body' },
    getHeader: { returns: 'unknown' },
    getFooter: { returns: 'unknown' },
    getAs: { returns: 'Blob' },
    saveAndClose: { returns: 'void' },
    getActiveSection: { returns: 'unknown' },
  },
  Body: {
    appendParagraph: { returns: 'unknown' },
    appendListItem: { returns: 'unknown' },
    appendTable: { returns: 'unknown' },
    appendImage: { returns: 'unknown' },
    appendPageBreak: { returns: 'unknown' },
    appendHorizontalRule: { returns: 'unknown' },
    getText: { returns: 'string' },
    setText: { returns: 'Body' },
    clear: { returns: 'Body' },
    editAsText: { returns: 'unknown' },
    findText: { returns: 'unknown' },
    replaceText: { returns: 'unknown' },
    getNumChildren: { returns: 'number' },
    getChild: { returns: 'unknown' },
  },
};

/**
 * Liste des types racine du registre qui correspondent à des **services
 * directement accessibles** (vs des types retournés intermédiaires).
 */
export const GAS_API_SERVICE_ROOTS = new Set<string>(
  Object.keys(GAS_API).filter((k) => /^(?:[A-Z][a-z]+)+(?:App|Service)$|^(?:ScriptApp|Utilities|Session|Logger|MailApp)$/.test(k)),
);
